"""add measurements table

Revision ID: 6646b5f6fb56
Revises: 90002c87e9f6
Create Date: 2025-08-14 01:28:58.197209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6646b5f6fb56'
down_revision = '90002c87e9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hip', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('hip')
        batch_op.drop_column('height')
        batch_op.drop_column('chest')
        batch_op.drop_column('weight')
        batch_op.drop_column('waist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waist', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('chest', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hip', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_member_id'))

    op.drop_table('measurements')
    # ### end Alembic commands ###
